server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-active: 200
    max-pool-prepared-statement-per-connection-size: 20
    max-wait: 60000
    min-idle: 5
    pool-prepared-statements: true
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/web-dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: 30000

mybatis-plus:
  configuration:
    cache-enabled: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    use-generated-keys: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.webdev.newtech.domain
pagehelper:
  helperDialect: mysql
  params: 'count=countSql '
  reasonable: true
  supportMethodsArguments: true

knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: "接口文档生成"
    email: ""
    concat: admin
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 测试接口
        api-rule: package
        api-rule-resources:
          - com.webdev.newtech.controller
